[profile.default]
src = "src"
test = 'tests'
script = 'scripts'
out = 'out'
libs = ['lib']

ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

optimizer = true
optimizer_runs = 200
solc = '0.8.30'
evm_version = 'shanghai'

fs_permissions = [
  { access = "read", path = "./out" },
]

remappings = [
  '@openzeppelin/=lib/openzeppelin-contracts/'
]

[fuzz]
runs = 10
max_test_rejects = 200

[rpc_endpoints]
testnet = "${RPC_TESTNET}"
