[profile.default]
src = "src"
test = 'tests'
script = 'scripts'
optimizer = true
optimizer_runs = 200
solc = '0.8.30'
evm_version = 'prague'
bytecode_hash = 'none'
out = 'out'
libs = ['lib']
remappings = []
fs_permissions = [
  { access = "write", path = "./reports" },
  { access = "read", path = "./out" },
  { access = "read", path = "./config" },
]
ffi = true

[fuzz]
runs = 10
max_test_rejects = 200

[rpc_endpoints]
testnet = "${RPC_TESTNET}"
