import { createClient, SupabaseClient as SupabaseClientType } from '@supabase/supabase-js'
import { Database } from '@/types/database'

/**
 * Supabase client for the frontend
 *
 * @dev Types are generated by `bun run db:gen` in the root directory
 */
export class SupabaseClient {
  private client: SupabaseClientType<Database>

  constructor() {
    const supabase = createClient<Database>(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
    )
    this.client = supabase
  }

  async find() {
    return await this.client.from('wallets').select().overrideTypes<Array<{ id: string }>>()
  }
}
